checks:

  title-fixer:
    enforce-check: false
    fixes:
      - replace: Octane\s+us
        with: OCTANE-US
      - replace: Octane\s+qs
        with: OCTANE-QS
      - replace: Octane\s+de
        with: OCTANE-DE

  title-validator:
    matches:
      - ^(OCTANE-US\d+).*
      - ^(OCTANE-QS\d+).*
      - ^(OCTANE-DE\d+).*
      - ^Revert\s"(OCTANE-US\d+).*"
      - ^Revert\s"(OCTANE-DE\d+).*"
      - ^Revert\s"(OCTANE-QS\d+).*"
    failure-message: |2
      Pull Request Validation Failed. The pull request title should follow the below case-sensitive patterns
      * `OCTANE-US/QS/DE12345 An optional small summary title`
      * `Revert "OCTANE-US/QS/DE12345 An optional small summary title"`

  codeowner: codeowner
    enforce-multiple: true