name: Pull Request Validation Workflow

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
    # branches to consider in the event; optional, defaults to all
    #branches:
     # - master

jobs:
  pr_lint:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: pr-lint-action@master
      with:
        title-regex: '^(OCTANE-US\d*).*'
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}